### ISSUE TITLE
Why do we track progress of DQM construction in per-bias detail?

### ISSUE THREAD

**Issue by randomir** [dwave-examples/cryptarithmetic#8]
Tracking/visualizing the progress of adding linear/quadratic biases does not seem that useful to me:
- the 8 or 28 biases are added instantaneously. If it was a huge number of biases and/or the process took longer, it would make sense;
- the output is noisy:
```
setting linear biases...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 30066.70it/s]
setting quadratic biases...
28it [00:00, 3990.91it/s]
adding penalty biases...
28it [00:00, 25158.64it/s]
```

**Comment by hbarovertwo** [comment]
Thanks for bringing that up. Due to the limitations on unique letter count it makes sense to remove this, and remove `tqdm` from requirements. PR to follow.
